---
name: sticht-ci
on: [push, release]
jobs:
  tox:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        toxenv:
          - py36,mypy
    env:
      PIP_INDEX_URL: https://pypi.python.org/simple
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - run: python -m pip install --upgrade pip
      - run: pip install coveralls tox==3.2 tox-pip-extensions==1.3.0 ephemeral-port-reserve
      - run: tox -i https://pypi.python.org/simple -e ${{ matrix.toxenv }}
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.6

    - name: Install Python dependencies
      run: pip install wheel

    - name: Create a Wheel file and source distribution
      run: python setup.py sdist bdist_wheel

    - name: Publish distribution package to PyPI
      uses: pypa/gh-action-pypi-publish@v1.2.2
      with:
        password: ${{ secrets.pypi_password }}
